/*
===============================================================================
MIS 443 - FINAL EXAM DATASET
Customer Insights Database - PostgreSQL

Instructions for students:
1. Create and connect to the database specified in Question 1.
2. Run this entire script in the Query Tool.
3. Do not modify the tables or data created by this script.

Important:
- This script does NOT create a database.
- All tables are created in the public schema.
- The students table is NOT included. Students must create it in Question 1(b).
===============================================================================
*/

BEGIN;

-- Allow the script to be rerun in a practice or testing database.
-- Child tables are removed before parent tables to respect foreign keys.
DROP TABLE IF EXISTS public.baskets;
DROP TABLE IF EXISTS public.orders;
DROP TABLE IF EXISTS public.products;
DROP TABLE IF EXISTS public.customers;
DROP TABLE IF EXISTS public.country;

-- -----------------------------------------------------------------------------
-- Table: country
-- Stores the countries in which orders are placed.
-- -----------------------------------------------------------------------------
CREATE TABLE public.country (
    country_id   INTEGER GENERATED BY DEFAULT AS IDENTITY,
    country_name VARCHAR(50) NOT NULL,
    head_office  VARCHAR(50) NOT NULL,
    CONSTRAINT pk_country PRIMARY KEY (country_id),
    CONSTRAINT uq_country_name UNIQUE (country_name)
);

-- -----------------------------------------------------------------------------
-- Table: customers
-- Stores customer profile and marketing-permission information.
-- -----------------------------------------------------------------------------
CREATE TABLE public.customers (
    customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    first_shop  DATE NOT NULL,
    age         INTEGER NOT NULL,
    rewards     VARCHAR(3) NOT NULL,
    can_email   VARCHAR(3) NOT NULL,
    CONSTRAINT pk_customers PRIMARY KEY (customer_id),
    CONSTRAINT chk_customer_age CHECK (age BETWEEN 18 AND 120),
    CONSTRAINT chk_customer_rewards CHECK (rewards IN ('yes', 'no')),
    CONSTRAINT chk_customer_can_email CHECK (can_email IN ('yes', 'no'))
);

-- -----------------------------------------------------------------------------
-- Table: products
-- Stores product categories and current unit prices.
-- -----------------------------------------------------------------------------
CREATE TABLE public.products (
    product_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    category   VARCHAR(50) NOT NULL,
    price      NUMERIC(10, 2) NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (product_id),
    CONSTRAINT chk_product_price CHECK (price > 0)
);

-- -----------------------------------------------------------------------------
-- Table: orders
-- Stores each customer order and its sales channel and country.
-- -----------------------------------------------------------------------------
CREATE TABLE public.orders (
    order_id      INTEGER GENERATED BY DEFAULT AS IDENTITY,
    customer_id   INTEGER NOT NULL,
    date_shop     DATE NOT NULL,
    sales_channel VARCHAR(20) NOT NULL,
    country_id    INTEGER NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (order_id),
    CONSTRAINT fk_orders_customer
        FOREIGN KEY (customer_id)
        REFERENCES public.customers (customer_id),
    CONSTRAINT fk_orders_country
        FOREIGN KEY (country_id)
        REFERENCES public.country (country_id),
    CONSTRAINT chk_order_sales_channel
        CHECK (sales_channel IN ('retail', 'online'))
);

-- -----------------------------------------------------------------------------
-- Table: baskets
-- Stores the products and quantities included in each order.
-- One product can appear only once in an order; quantity records units purchased.
-- -----------------------------------------------------------------------------
CREATE TABLE public.baskets (
    order_id   INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    quantity   INTEGER NOT NULL,
    CONSTRAINT pk_baskets PRIMARY KEY (order_id, product_id),
    CONSTRAINT fk_baskets_order
        FOREIGN KEY (order_id)
        REFERENCES public.orders (order_id),
    CONSTRAINT fk_baskets_product
        FOREIGN KEY (product_id)
        REFERENCES public.products (product_id),
    CONSTRAINT chk_basket_quantity CHECK (quantity > 0)
);

-- -----------------------------------------------------------------------------
-- Sample data
-- -----------------------------------------------------------------------------
INSERT INTO public.country (country_id, country_name, head_office)
VALUES
    (1, 'UK',    'London'),
    (2, 'USA',   'New York'),
    (3, 'China', 'Beijing');

INSERT INTO public.customers
    (customer_id, first_shop, age, rewards, can_email)
VALUES
    (1, '2022-03-20', 23, 'yes', 'no'),
    (2, '2022-03-25', 26, 'no',  'no'),
    (3, '2022-04-06', 32, 'no',  'no'),
    (4, '2022-04-13', 25, 'yes', 'yes'),
    (5, '2022-04-22', 49, 'yes', 'yes'),
    (6, '2022-06-18', 28, 'yes', 'no'),
    (7, '2022-06-30', 36, 'no',  'no'),
    (8, '2022-07-04', 37, 'yes', 'yes');

INSERT INTO public.products (product_id, category, price)
VALUES
    (1, 'food',     5.99),
    (2, 'sports',  12.49),
    (3, 'vitamins', 6.99),
    (4, 'food',     0.89),
    (5, 'vitamins',15.99);

INSERT INTO public.orders
    (order_id, customer_id, date_shop, sales_channel, country_id)
VALUES
    (1, 1, '2023-01-16', 'retail', 1),
    (2, 4, '2023-01-20', 'retail', 1),
    (3, 2, '2023-01-25', 'retail', 2),
    (4, 3, '2023-01-25', 'online', 1),
    (5, 1, '2023-01-28', 'retail', 3),
    (6, 5, '2023-02-02', 'online', 1),
    (7, 6, '2023-02-05', 'retail', 1),
    (8, 3, '2023-02-11', 'online', 3);

INSERT INTO public.baskets (order_id, product_id, quantity)
VALUES
    (1, 1, 1),
    (1, 2, 1),
    (1, 5, 1),
    (2, 4, 1),
    (3, 3, 1),
    (4, 2, 1),
    (4, 1, 1),
    (5, 3, 1),
    (5, 5, 1),
    (6, 4, 1),
    (6, 3, 1),
    (6, 1, 1),
    (7, 2, 1),
    (7, 1, 1),
    (8, 3, 2);

-- Keep identity-generated values synchronized with the explicitly inserted IDs.
SELECT setval(pg_get_serial_sequence('public.country', 'country_id'),
              (SELECT MAX(country_id) FROM public.country));
SELECT setval(pg_get_serial_sequence('public.customers', 'customer_id'),
              (SELECT MAX(customer_id) FROM public.customers));
SELECT setval(pg_get_serial_sequence('public.products', 'product_id'),
              (SELECT MAX(product_id) FROM public.products));
SELECT setval(pg_get_serial_sequence('public.orders', 'order_id'),
              (SELECT MAX(order_id) FROM public.orders));

COMMIT;

-- -----------------------------------------------------------------------------
-- Verification: expected row counts are 3, 8, 8, 5, and 15.
-- -----------------------------------------------------------------------------
SELECT 'country' AS table_name, COUNT(*) AS row_count FROM public.country
UNION ALL
SELECT 'customers', COUNT(*) FROM public.customers
UNION ALL
SELECT 'orders', COUNT(*) FROM public.orders
UNION ALL
SELECT 'products', COUNT(*) FROM public.products
UNION ALL
SELECT 'baskets', COUNT(*) FROM public.baskets
ORDER BY table_name;
