/*
===============================================================================
MIS 443 - FINANCE ANALYSIS DATASET - POSTGRESQL

Instructions:
1. Create and connect to the database specified in Question 1.
2. Run this entire script.
3. Do not modify the supplied tables or data.

This script does not create a database.
All supplied tables are created in the public schema.
===============================================================================
*/

BEGIN;

DROP TABLE IF EXISTS public.transactions;
DROP TABLE IF EXISTS public.accounts;
DROP TABLE IF EXISTS public.branches;
DROP TABLE IF EXISTS public.customers;

CREATE TABLE public.customers (
    customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    first_name  VARCHAR(50) NOT NULL,
    last_name   VARCHAR(50) NOT NULL,
    city        VARCHAR(50) NOT NULL,
    state       CHAR(2) NOT NULL,
    CONSTRAINT pk_customers PRIMARY KEY (customer_id),
    CONSTRAINT chk_customer_state CHECK (char_length(state) = 2)
);

CREATE TABLE public.branches (
    branch_id   INTEGER GENERATED BY DEFAULT AS IDENTITY,
    branch_name VARCHAR(50) NOT NULL,
    city        VARCHAR(50) NOT NULL,
    state       CHAR(2) NOT NULL,
    CONSTRAINT pk_branches PRIMARY KEY (branch_id),
    CONSTRAINT chk_branch_state CHECK (char_length(state) = 2)
);

CREATE TABLE public.accounts (
    account_id   INTEGER GENERATED BY DEFAULT AS IDENTITY,
    customer_id  INTEGER NOT NULL,
    branch_id    INTEGER NOT NULL,
    account_type VARCHAR(20) NOT NULL,
    balance      NUMERIC(12, 2) NOT NULL,
    CONSTRAINT pk_accounts PRIMARY KEY (account_id),
    CONSTRAINT fk_accounts_customer
        FOREIGN KEY (customer_id) REFERENCES public.customers (customer_id),
    CONSTRAINT fk_accounts_branch
        FOREIGN KEY (branch_id) REFERENCES public.branches (branch_id),
    CONSTRAINT chk_account_type
        CHECK (account_type IN ('Checking', 'Savings', 'Credit Card'))
);

CREATE TABLE public.transactions (
    transaction_id   INTEGER GENERATED BY DEFAULT AS IDENTITY,
    account_id       INTEGER NOT NULL,
    transaction_date DATE NOT NULL,
    amount           NUMERIC(12, 2) NOT NULL,
    CONSTRAINT pk_transactions PRIMARY KEY (transaction_id),
    CONSTRAINT fk_transactions_account
        FOREIGN KEY (account_id) REFERENCES public.accounts (account_id),
    CONSTRAINT chk_transaction_amount CHECK (amount <> 0)
);

INSERT INTO public.customers
    (customer_id, first_name, last_name, city, state)
VALUES
    (1, 'John',     'Doe',     'New York',     'NY'),
    (2, 'Jane',     'Doe',     'New York',     'NY'),
    (3, 'Bob',      'Smith',   'San Francisco','CA'),
    (4, 'Alice',    'Johnson', 'San Francisco','CA'),
    (5, 'Michael',  'Lee',     'Los Angeles',  'CA'),
    (6, 'Jennifer', 'Wang',    'Los Angeles',  'CA');

INSERT INTO public.branches
    (branch_id, branch_name, city, state)
VALUES
    (1,  'Main',               'New York',      'NY'),
    (2,  'Downtown',           'San Francisco', 'CA'),
    (3,  'West LA',            'Los Angeles',   'CA'),
    (4,  'East LA',            'Los Angeles',   'CA'),
    (5,  'Uptown',             'New York',      'NY'),
    (6,  'Financial District', 'San Francisco', 'CA'),
    (7,  'Midtown',            'New York',      'NY'),
    (8,  'South Bay',          'San Francisco', 'CA'),
    (9,  'Downtown',           'Los Angeles',   'CA'),
    (10, 'Chinatown',          'New York',      'NY'),
    (11, 'Marina',             'San Francisco', 'CA'),
    (12, 'Beverly Hills',      'Los Angeles',   'CA'),
    (13, 'Brooklyn',           'New York',      'NY'),
    (14, 'North Beach',        'San Francisco', 'CA'),
    (15, 'Pasadena',           'Los Angeles',   'CA');

INSERT INTO public.accounts
    (account_id, customer_id, branch_id, account_type, balance)
VALUES
    (1,  1, 5,  'Checking',     1000.00),
    (2,  1, 5,  'Savings',      5000.00),
    (3,  2, 1,  'Checking',     2500.00),
    (4,  2, 1,  'Savings',     10000.00),
    (5,  3, 2,  'Checking',     7500.00),
    (6,  3, 2,  'Savings',     15000.00),
    (7,  4, 8,  'Checking',     5000.00),
    (8,  4, 8,  'Savings',     20000.00),
    (9,  5, 14, 'Checking',    10000.00),
    (10, 5, 14, 'Savings',     50000.00),
    (11, 6, 2,  'Checking',     5000.00),
    (12, 6, 2,  'Savings',     10000.00),
    (13, 1, 5,  'Credit Card',  -500.00),
    (14, 2, 1,  'Credit Card', -1000.00),
    (15, 3, 2,  'Credit Card', -2000.00);

INSERT INTO public.transactions
    (transaction_id, account_id, transaction_date, amount)
VALUES
    (1,  1, '2022-01-01',  -500.00),
    (2,  1, '2022-01-02',  -250.00),
    (3,  2, '2022-01-03',  1000.00),
    (4,  3, '2022-01-04', -1000.00),
    (5,  3, '2022-01-05',   500.00),
    (6,  4, '2022-01-06',  1000.00),
    (7,  4, '2022-01-07',  -500.00),
    (8,  5, '2022-01-08', -2500.00),
    (9,  6, '2022-01-09',   500.00),
    (10, 6, '2022-01-10', -1000.00),
    (11, 7, '2022-01-11',  -500.00),
    (12, 7, '2022-01-12',  -250.00),
    (13, 8, '2022-01-13',  1000.00),
    (14, 8, '2022-01-14', -1000.00),
    (15, 9, '2022-01-15',   500.00);

SELECT setval(pg_get_serial_sequence('public.customers', 'customer_id'),
              (SELECT MAX(customer_id) FROM public.customers));
SELECT setval(pg_get_serial_sequence('public.branches', 'branch_id'),
              (SELECT MAX(branch_id) FROM public.branches));
SELECT setval(pg_get_serial_sequence('public.accounts', 'account_id'),
              (SELECT MAX(account_id) FROM public.accounts));
SELECT setval(pg_get_serial_sequence('public.transactions', 'transaction_id'),
              (SELECT MAX(transaction_id) FROM public.transactions));

COMMIT;

-- Expected row counts: accounts 15, branches 15, customers 6, transactions 15.
SELECT 'accounts' AS table_name, COUNT(*) AS row_count FROM public.accounts
UNION ALL
SELECT 'branches', COUNT(*) FROM public.branches
UNION ALL
SELECT 'customers', COUNT(*) FROM public.customers
UNION ALL
SELECT 'transactions', COUNT(*) FROM public.transactions
ORDER BY table_name;
